spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost:5432/${YOUR_DOGGY_DB}
    username: ${YOUR_DOGGY_DB_USER}
    password: ${YOUR_DOGGY_DB_PASSWORD}
  ai:
    openai:
      api-key: ${PERPLEXITY_API_KEY}
      base-url: https://api.perplexity.ai
      chat:
        completions-path: /chat/completions
        options:
          model: sonar-pro
      embedding:
        enabled: false
    ollama:
      base-url: http://localhost:11434 # Adjust if different
      embedding:
        enabled: true
        model: nomic-embed-text # Smaller models https://ollama.com/blog/embedding-models
    vectorstore:
      pgvector:
        schema-name: ${YOUR_DOGGY_DB}
        initialize-schema: true
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 768
